INSERT INTO shoe_store.product_info VALUES 
("KIDS UNISEX RUNNING SHOES", "ALPHABOUNCE_AMS_SHOES","Description: When each footstrike gets a cushioned landing, you feel like you can run all day. These running shoes for juniors are built with BOUNCE™ for enhanced comfort. A FORGEDMESH upper expands with your foot throughout your stride and provides lightweight support that keeps you going.","Color: Clear Grey", 90),
("KIDS UNISEX ORIGINAL SHOES", "EQT_RUNNING_SUPPORT","Description: The Equipment running shoe first stepped out on the track in the early '90s. Refreshed for the street, these juniors' shoes are a modern take on the iconic sneaker. The upper is made with mesh and faux suede, and it features reflective details. A signature heel cage stays true to original design.", "Color: Core Black", 70),
("MEN'S ORIGINAL SHOES", "GAZELLE_SHOES", "Description: Ultimate simplicity for three decades and counting. This men's version of the Gazelle honors the favorite version of 1991, with the same materials, colors, textures and proportions as the original. The leather upper features contrast 3-Stripes and heel tab that echo the early-'90s style.", "Color: Collegiate Royal", 80),
("WOMEN'S ORIGINAL SHOES", "NMD_R1_SHOES", "Description: NMD footwear continues on its progressive spiral in fresh new combinations of urban style and running-inspired design. These women's shoes feature a stretchy knit upper for a sleek look. A reflective heel stands out, and so do the matching 3-Stripes. Midsole boost™ keeps energy coming when you need it. Best of all, they feel as comfy as a sock.", "Color: Core Black", 170),
("MEN'S RUNNING SHOES", "PUREBOOST_SHOES", "Description: Ultimate simplicity for three decades and counting. This men's version of the Gazelle honors the favorite version of 1991, with the same materials, colors, textures and proportions as the original. The leather upper features contrast 3-Stripes and heel tab that echo the early-'90s style.","Color: Core Black",200),
("WOMEN'S RUNNING SHOES", "PUREBOOST_X_SHOES", "Description: Boost™ is our most responsive cushioning ever: The more energy you give, the more you get. Extended TORSION® SYSTEM for energy return in the forefoot and natural integrity in the midfoot Lace-free sock construction. Free-floating arch under the midfoot; Allover graphic inspired by Aramis testing. Adaptive dynamic fit for optimal flexibility and zoned support.", "Color: Bright Red", 150),
("KIDS UNISEX RUNNING SHOES", "RAPIDARUN_UNCAGED_SHOES", "Description: They won't have to imagine what it feels like to run on clouds. These kids' running shoes will let them experience it. A soft cloudfoam SURROUND midsole with memory foam molds to the foot with every step while giving extra support at the forefoot and heel.", "Color: Solid Grey", 650),
("MEN'S ORIGINAL SHOES", "STAN_SMITH_BOOST_SHOES", "Description: A classic since the '70s, this sneaker icon gets an update with modern materials. These men's Stan Smith shoes feature energy-returning boost™ in the midsole for an ultra-comfy stride. Built in lightweight adidas Primeknit for a sock-like fit, they have the signature Stan Smith tongue and label.", "Color: Collegiate Navy", 140),
("MEN'S ORIGINAL SHOES", "SUPERSTAR_BOOST_SHOES", "Description: Launched in 1970 as a revolutionary basketball shoe, the adidas Superstar shoe was the sport's first low-top leather sneaker. In '80s New York City, hip hop heroes lifted a pair up on stage and dedicated a song to them. A legend was born. As fresh as ever, this modern version of the shoes has the energy-returning feel of boost™. They're built with a soft all-leather upper and boast all the beloved details, including the famous rubber shell toe and herringbone-pattern cupsole.", "Color: Core Black", 120),
("WOMEN'S ORIGINAL SHOES", "SUPERSTAR_SHOES", "Description: The shell toe takes a trip to the tropics. A true original since 1970, these Superstar sneakers have been revamped with an island vibe. Infused with the sights and sounds of Southern climes, these shoes are designed in collaboration with Brazilian label The FARM Company. These women's Superstar shoes step out in lush florals. Bursting with blooms, they have an Asian-inspired print on a twill upper. Finished with the iconic serrated 3-Stripes, the rubber shell toe and the herringbone cupsole.", "Color: White Ftw", 80),
("KIDS UNISEX ORIGINAL SHOES", "TUBULAR_INVADER_STRAP_SHOE", "Description: Progressive street-style kicks with an identity all their own. These mid-cut juniors' shoes blend signature Tubular details with design cues sourced from the Invader basketball sneaker of the 1980s. They come in tonal camouflage suede with an adjustable midfoot strap and a two-tone rubber cupsole.", "Color: Olive Cargo", 85),
("WOMEN'S RUNNING SHOES", "ULTRABOOST_X_CLIMA_SHOES", "Description: Give your last-best run some serious competition in these women's shoes built with ultra-cushioned boost™. Designed to respond to the way your foot moves through each stride, the shoes feature a floating arch and an adidas Primeknit upper that hugs your foot throughout the gait cycle. boost™ delivers maximum energy return, and a stretchy outsole flexes to adapt to the way your foot strikes the ground.", "Color: Glow Orange", 180);
